import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          black:   '#050507',
          dark:    '#0C0C12',
          card:    '#111118',
          border:  'rgba(255,255,255,0.07)',
          gold:    '#D4A017',
          'gold-bright': '#F0C040',
          'gold-dim':    'rgba(212,160,23,0.14)',
          'gold-glow':   'rgba(240,192,64,0.25)',
          orange:  '#FF4D00',
          blue:    '#00D4FF',
          'blue-dim':    'rgba(0,212,255,0.12)',
          teal:    '#00E5CC',
          purple:  '#8B5CF6',
          gray:    '#6B7280',
          muted:   '#4B5563',
          light:   '#F9FAFB',
        },
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      animation: {
        'fade-up':      'fadeUp 0.7s cubic-bezier(0.23,1,0.32,1) both',
        'fade-in':      'fadeIn 0.5s ease both',
        'fade-down':    'fadeDown 0.5s ease both',
        'float':        'float 5s ease-in-out infinite',
        'float-slow':   'float 8s ease-in-out infinite',
        'scan':         'scan 2.5s ease-in-out infinite',
        'scan-v':       'scanV 2s ease-in-out infinite',
        'marquee':      'marquee 28s linear infinite',
        'marquee-rev':  'marqueeRev 28s linear infinite',
        'pulse-slow':   'pulse 4s ease-in-out infinite',
        'spin-slow':    'spin 12s linear infinite',
        'spin-med':     'spin 5s linear infinite',
        'slide-in':     'slideIn 0.45s cubic-bezier(0.23,1,0.32,1) both',
        'slide-up':     'slideUp 0.4s cubic-bezier(0.23,1,0.32,1) both',
        'glow-pulse':   'glowPulse 3s ease-in-out infinite',
        'shimmer':      'shimmer 2.2s linear infinite',
        'bounce-sm':    'bounceSm 1s ease-in-out infinite',
        'scale-in':     'scaleIn 0.35s cubic-bezier(0.23,1,0.32,1) both',
        'rotate-in':    'rotateIn 0.5s cubic-bezier(0.23,1,0.32,1) both',
        'progress':     'progress 1.8s ease-in-out both',
        'orbit':        'orbit 8s linear infinite',
        'morph':        'morph 8s ease-in-out infinite',
      },
      keyframes: {
        fadeUp:     { from: { opacity: '0', transform: 'translateY(32px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeDown:   { from: { opacity: '0', transform: 'translateY(-16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:     { from: { opacity: '0' }, to: { opacity: '1' } },
        float:      { '0%,100%': { transform: 'translateY(0px) rotate(0deg)' }, '33%': { transform: 'translateY(-12px) rotate(1deg)' }, '66%': { transform: 'translateY(-6px) rotate(-1deg)' } },
        scan:       { '0%,100%': { opacity: '0.2', transform: 'scaleX(0.3)' }, '50%': { opacity: '1', transform: 'scaleX(1)' } },
        scanV:      { '0%': { transform: 'translateY(-100%)', opacity: '0' }, '20%': { opacity: '1' }, '80%': { opacity: '1' }, '100%': { transform: 'translateY(200%)', opacity: '0' } },
        marquee:    { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        marqueeRev: { from: { transform: 'translateX(-50%)' }, to: { transform: 'translateX(0)' } },
        slideIn:    { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        slideUp:    { from: { transform: 'translateY(100%)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        glowPulse:  { '0%,100%': { boxShadow: '0 0 20px rgba(212,160,23,0.2)' }, '50%': { boxShadow: '0 0 60px rgba(212,160,23,0.5), 0 0 120px rgba(212,160,23,0.2)' } },
        shimmer:    { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        bounceSm:   { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
        scaleIn:    { from: { opacity: '0', transform: 'scale(0.88)' }, to: { opacity: '1', transform: 'scale(1)' } },
        rotateIn:   { from: { opacity: '0', transform: 'rotate(-8deg) scale(0.9)' }, to: { opacity: '1', transform: 'rotate(0deg) scale(1)' } },
        progress:   { from: { width: '0%' }, to: { width: 'var(--progress, 100%)' } },
        orbit:      { from: { transform: 'rotate(0deg) translateX(80px) rotate(0deg)' }, to: { transform: 'rotate(360deg) translateX(80px) rotate(-360deg)' } },
        morph:      { '0%,100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' }, '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' } },
      },
      backdropBlur: { xs: '2px', '4xl': '80px' },
      boxShadow: {
        'gold':   '0 0 40px rgba(212,160,23,0.3), 0 0 80px rgba(212,160,23,0.1)',
        'gold-sm':'0 0 20px rgba(212,160,23,0.25)',
        'blue':   '0 0 40px rgba(0,212,255,0.3)',
        'card':   '0 32px 64px rgba(0,0,0,0.5)',
        'card-lg':'0 60px 120px rgba(0,0,0,0.6)',
        'up':     '0 -20px 60px rgba(0,0,0,0.4)',
      },
    },
  },
  plugins: [],
}

export default config
